#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
모든 영어 JSON 파일의 meaning_ko 필드를 한국어 뜻으로 교체하는 스크립트
"""

import json
import os
from pathlib import Path

# 영어 단어별 한국어 뜻 사전
KOREAN_MEANINGS = {
    # 기초다지기 일상회화
    "hello": "안녕하세요",
    "yes": "네",
    "no": "아니요", 
    "thank": "감사하다",
    "please": "부탁하다",
    "sorry": "미안하다",
    "welcome": "환영하다",
    "bye": "안녕",
    "good": "좋은",
    "bad": "나쁜",
    "help": "도움",
    "talk": "말하다",
    "speak": "말하다",
    "listen": "듣다",
    "ask": "묻다",
    "answer": "대답하다",
    "tell": "말하다",
    "say": "말하다",
    "name": "이름",
    "meet": "만나다",
    "friend": "친구",
    "family": "가족",
    "happy": "행복한",
    "sad": "슬픈",
    "like": "좋아하다",
    "want": "원하다",
    "need": "필요하다",
    "have": "가지다",
    "get": "얻다",
    "give": "주다",
    "know": "알다",
    "think": "생각하다",
    "feel": "느끼다",
    "see": "보다",
    "hear": "듣다",
    "come": "오다",
    "go": "가다",
    "eat": "먹다",
    "drink": "마시다",
    "sleep": "자다",
    "morning": "아침",
    "afternoon": "오후",
    "evening": "저녁",
    "night": "밤",
    "today": "오늘",
    "tomorrow": "내일",
    "yesterday": "어제",
    "time": "시간",
    "day": "날",
    "week": "주",
    
    # 기초다지기 비즈니스
    "work": "일",
    "job": "직업",
    "office": "사무실",
    "company": "회사",
    "boss": "상사",
    "manager": "관리자",
    "worker": "직원",
    "team": "팀",
    "meeting": "회의",
    "email": "이메일",
    "call": "전화",
    "phone": "전화기",
    "computer": "컴퓨터",
    "paper": "종이",
    "pen": "펜",
    "desk": "책상",
    "chair": "의자",
    "file": "파일",
    "document": "문서",
    "report": "보고서",
    "money": "돈",
    "pay": "지불하다",
    "salary": "급여",
    "price": "가격",
    "sell": "팔다",
    "buy": "사다",
    "customer": "고객",
    "client": "클라이언트",
    "service": "서비스",
    "product": "제품",
    "schedule": "일정",
    "early": "이른",
    "late": "늦은",
    "busy": "바쁜",
    "free": "자유로운",
    "start": "시작하다",
    "finish": "끝내다",
    "break": "휴식",
    "lunch": "점심",
    "month": "월",
    "year": "년",
    "plan": "계획",
    "goal": "목표",
    "problem": "문제",
    "solution": "해결책",
    
    # 기초다지기 여행
    "trip": "여행",
    "travel": "여행하다",
    "visit": "방문하다",
    "arrive": "도착하다",
    "leave": "떠나다",
    "stay": "머물다",
    "hotel": "호텔",
    "room": "방",
    "airport": "공항",
    "plane": "비행기",
    "train": "기차",
    "bus": "버스",
    "taxi": "택시",
    "car": "차",
    "ticket": "티켓",
    "passport": "여권",
    "bag": "가방",
    "luggage": "짐",
    "map": "지도",
    "guide": "가이드",
    "tour": "투어",
    "photo": "사진",
    "camera": "카메라",
    "beach": "해변",
    "mountain": "산",
    "city": "도시",
    "country": "나라",
    "place": "장소",
    "food": "음식",
    "restaurant": "레스토랑",
    "shop": "가게",
    "cheap": "싼",
    "expensive": "비싼",
    "book": "예약하다",
    "reserve": "예약하다",
    "check": "확인하다",
    "in": "안",
    "out": "밖",
    "lost": "잃어버린",
    "find": "찾다",
    "where": "어디",
    "when": "언제",
    "how": "어떻게",
    "far": "먼",
    
    # 기초다지기 뉴스-시사
    "news": "뉴스",
    "report": "보고서",
    "story": "이야기",
    "read": "읽다",
    "watch": "보다",
    "listen": "듣다",
    "tell": "말하다",
    "know": "알다",
    "hear": "듣다",
    "see": "보다",
    "today": "오늘",
    "now": "지금",
    "new": "새로운",
    "old": "오래된",
    "big": "큰",
    "small": "작은",
    "important": "중요한",
    "happen": "일어나다",
    "event": "사건",
    "thing": "것",
    "people": "사람들",
    "person": "사람",
    "man": "남자",
    "woman": "여자",
    "child": "아이",
    "place": "장소",
    "city": "도시",
    "country": "나라",
    "world": "세계",
    "home": "집",
    "good": "좋은",
    "bad": "나쁜",
    "right": "옳은",
    "wrong": "틀린",
    "true": "진실",
    "false": "거짓",
    "say": "말하다",
    "talk": "말하다",
    "speak": "말하다",
    "ask": "묻다",
    "answer": "대답하다",
    "think": "생각하다",
    "believe": "믿다",
    "feel": "느끼다",
    "like": "좋아하다",
    "want": "원하다",
    "need": "필요하다",
    "help": "도움",
    "problem": "문제",
    "change": "변화",
    
    # 표현력확장 레벨
    "conversation": "대화",
    "discuss": "논의하다",
    "explain": "설명하다",
    "describe": "묘사하다",
    "opinion": "의견",
    "agree": "동의하다",
    "disagree": "동의하지 않다",
    "suggest": "제안하다",
    "recommend": "추천하다",
    "advice": "조언",
    "apologize": "사과하다",
    "compliment": "칭찬",
    "introduce": "소개하다",
    "interrupt": "방해하다",
    "mention": "언급하다",
    "express": "표현하다",
    "communicate": "소통하다",
    "understand": "이해하다",
    "misunderstand": "오해하다",
    "clarify": "명확히 하다",
    "confirm": "확인하다",
    "remind": "상기시키다",
    "promise": "약속하다",
    "refuse": "거절하다",
    "accept": "받아들이다",
    "reject": "거부하다",
    "persuade": "설득하다",
    "argue": "논쟁하다",
    "debate": "토론하다",
    "negotiate": "협상하다",
    "gossip": "소문",
    "rumor": "소문",
    "whisper": "속삭이다",
    "shout": "소리치다",
    "mumble": "중얼거리다",
    "stutter": "말을 더듬다",
    "emphasize": "강조하다",
    "imply": "암시하다",
    "comment": "논평하다",
    "remark": "발언",
    "statement": "성명",
    "question": "질문",
    "response": "응답",
    "feedback": "피드백",
    "criticism": "비판",
    "praise": "칭찬",
    "gesture": "몸짓",
    "expression": "표현",
    "tone": "어조",
    "attitude": "태도",
    
    # 비즈니스 원어민수준 용어
    "corporation": "기업",
    "enterprise": "기업",
    "organization": "조직",
    "department": "부서",
    "employee": "직원",
    "colleague": "동료",
    "supervisor": "상급자",
    "executive": "임원",
    "director": "이사",
    "administrator": "관리자",
    "position": "직책",
    "responsibility": "책임",
    "assignment": "과제",
    "project": "프로젝트",
    "deadline": "마감일",
    "presentation": "발표",
    "proposal": "제안",
    "contract": "계약",
    "agreement": "합의",
    "negotiation": "협상",
    "transaction": "거래",
    "investment": "투자",
    "profit": "이익",
    "loss": "손실",
    "revenue": "수익",
    "expense": "비용",
    "budget": "예산",
    "finance": "금융",
    "accounting": "회계",
    "marketing": "마케팅",
    "advertising": "광고",
    "sales": "판매",
    "distribution": "유통",
    "supply": "공급",
    "demand": "수요",
    "inventory": "재고",
    "stock": "주식",
    "quality": "품질",
    "efficiency": "효율성",
    "productivity": "생산성",
    "performance": "성과",
    "evaluation": "평가",
    "promotion": "승진",
    "recruitment": "채용",
    "training": "교육",
    "competition": "경쟁",
    "strategy": "전략",
    "analysis": "분석",
    "research": "연구",
    
    # 여행 원어민수준 용어
    "destination": "목적지",
    "itinerary": "여행 일정",
    "reservation": "예약",
    "accommodation": "숙박",
    "departure": "출발",
    "arrival": "도착",
    "boarding": "탑승",
    "customs": "세관",
    "immigration": "입국심사",
    "security": "보안",
    "baggage": "수하물",
    "suitcase": "여행가방",
    "backpack": "배낭",
    "traveler": "여행자",
    "tourist": "관광객",
    "vacation": "휴가",
    "holiday": "휴일",
    "adventure": "모험",
    "excursion": "소풍",
    "sightseeing": "관광",
    "landmark": "랜드마크",
    "monument": "기념비",
    "museum": "박물관",
    "gallery": "갤러리",
    "attraction": "관광지",
    "scenic": "경치 좋은",
    "hospitality": "환대",
    "reception": "리셉션",
    "concierge": "컨시어지",
    "amenities": "편의시설",
    "facilities": "시설",
    "transportation": "교통",
    "schedule": "일정",
    "delay": "지연",
    "cancellation": "취소",
    "refund": "환불",
    "exchange": "환전",
    "currency": "통화",
    "souvenir": "기념품",
    "local": "현지의",
    "native": "원주민",
    "foreign": "외국의",
    "international": "국제적인",
    "domestic": "국내의",
    "culture": "문화",
    "tradition": "전통",
    "explore": "탐험하다",
    "discover": "발견하다",
    "wander": "배회하다",
    "navigate": "항해하다",
    
    # 뉴스-시사 원어민수준 용어
    "journalism": "저널리즘",
    "reporter": "기자",
    "correspondent": "특파원",
    "editor": "편집자",
    "publisher": "출판사",
    "broadcast": "방송",
    "media": "미디어",
    "press": "언론",
    "newspaper": "신문",
    "magazine": "잡지",
    "article": "기사",
    "headline": "헤드라인",
    "coverage": "보도",
    "investigation": "수사",
    "interview": "인터뷰",
    "statement": "성명",
    "announcement": "발표",
    "declaration": "선언",
    "disclosure": "공개",
    "revelation": "폭로",
    "incident": "사건",
    "occurrence": "발생",
    "development": "발전",
    "situation": "상황",
    "circumstance": "상황",
    "condition": "조건",
    "politics": "정치",
    "government": "정부",
    "election": "선거",
    "policy": "정책",
    "economy": "경제",
    "market": "시장",
    "crisis": "위기",
    "conflict": "갈등",
    "dispute": "분쟁",
    "controversy": "논란",
    "debate": "토론",
    "discussion": "논의",
    "opinion": "의견",
    "perspective": "관점",
    "analysis": "분석",
    "commentary": "논평",
    "criticism": "비판",
    "review": "검토",
    "evaluation": "평가",
    "assessment": "평가",
    "survey": "조사",
    "statistics": "통계",
    "data": "데이터",
    "evidence": "증거",
    "proof": "증명",
    
    # 원어민수준 원어민수준 용어
    "articulate": "명확하게 표현하다",
    "eloquent": "웅변의",
    "rhetoric": "수사학",
    "diplomatic": "외교적인",
    "tactful": "재치 있는",
    "assertive": "단호한",
    "confrontation": "대립",
    "mediation": "중재",
    "reconciliation": "화해",
    "discourse": "담론",
    "dialogue": "대화",
    "monologue": "독백",
    "soliloquy": "독백",
    "vernacular": "방언",
    "colloquial": "구어체의",
    "jargon": "전문용어",
    "euphemism": "완곡어법",
    "metaphor": "은유",
    "analogy": "비유",
    "inference": "추론",
    "connotation": "함축",
    "denotation": "의미",
    "ambiguity": "애매함",
    "nuance": "뉘앙스",
    "subtlety": "미묘함",
    "implication": "함축",
    "persuasion": "설득",
    "manipulation": "조작",
    "propaganda": "선전",
    "eloquence": "웅변",
    "articulation": "명확한 표현",
    "deliberation": "숙고",
    "contemplation": "명상",
    "rumination": "깊이 생각함",
    "introspection": "자기 성찰",
    "retrospection": "회상",
    "philosophical": "철학적인",
    "theoretical": "이론적인",
    "abstract": "추상적인",
    "conceptual": "개념적인",
    "hypothetical": "가설적인",
    "speculative": "추측적인",
    "intellectual": "지적인",
    "cognitive": "인지적인",
    "analytical": "분석적인",
    "critical": "비판적인",
    "rational": "합리적인",
    "logical": "논리적인",
    
    # 원어민수준 비즈니스 용어
    "conglomerate": "대기업",
    "subsidiary": "자회사",
    "affiliate": "계열사",
    "merger": "합병",
    "acquisition": "인수",
    "consolidation": "통합",
    "restructuring": "구조조정",
    "diversification": "다각화",
    "specialization": "전문화",
    "monopoly": "독점",
    "oligopoly": "과점",
    "entrepreneurship": "기업가정신",
    "venture": "벤처",
    "startup": "스타트업",
    "innovation": "혁신",
    "disruption": "파괴",
    "transformation": "변화",
    "sustainability": "지속가능성",
    "scalability": "확장성",
    "optimization": "최적화",
    "automation": "자동화",
    "digitalization": "디지털화",
    "stakeholder": "이해관계자",
    "shareholder": "주주",
    "dividend": "배당",
    "equity": "자본",
    "liability": "부채",
    "asset": "자산",
    "depreciation": "감가상각",
    "amortization": "상각",
    "valuation": "평가",
    "liquidation": "청산",
    "bankruptcy": "파산",
    "insolvency": "지급불능",
    "foreclosure": "압류",
    "compliance": "준수",
    "regulation": "규제",
    "legislation": "입법",
    "litigation": "소송",
    "arbitration": "중재",
    "mediation": "조정",
    "intellectual": "지적",
    "proprietary": "독점적인",
    "patent": "특허",
    "trademark": "상표",
    "copyright": "저작권",
    "franchise": "프랜차이즈",
    "syndicate": "신디케이트",
    "consortium": "컨소시엄",
    "collaboration": "협력",
    "partnership": "파트너십",
    "alliance": "동맹",
    "cooperation": "협력",
    
    # 원어민수준 여행 용어
    "expedition": "탐험",
    "pilgrimage": "순례",
    "odyssey": "장기 여행",
    "sojourn": "체류",
    "itinerant": "유목민의",
    "nomadic": "유목의",
    "cosmopolitan": "국제적인",
    "expatriate": "재외국민",
    "diaspora": "디아스포라",
    "displacement": "이주",
    "migration": "이주",
    "emigration": "이민",
    "colonization": "식민지화",
    "exploration": "탐험",
    "pioneering": "개척적인",
    "traversal": "횡단",
    "circumnavigation": "세계일주",
    "embarkation": "승선",
    "disembarkation": "하선",
    "layover": "경유",
    "stopover": "경유지",
    "transit": "환승",
    "consulate": "영사관",
    "embassy": "대사관",
    "jurisdiction": "관할권",
    "sovereignty": "주권",
    "territory": "영토",
    "frontier": "국경",
    "boundary": "경계",
    "demarcation": "경계선",
    "infrastructure": "인프라",
    "logistics": "물류",
    "provisions": "식량",
    "sustenance": "생계",
    "subsistence": "생존",
    "indigenous": "원주민의",
    "aboriginal": "원주민의",
    "ethnic": "민족의",
    "multicultural": "다문화의",
    "intercultural": "문화간의",
    "transnational": "초국가적인",
    "globalization": "글로벌화",
    "acculturation": "문화적응",
    "assimilation": "동화",
    "adaptation": "적응",
    "orientation": "방향",
    "disorientation": "혼란",
    "alienation": "소외",
    
    # 원어민수준 뉴스-시사 용어
    "investigative": "수사적인",
    "editorial": "사설",
    "documentary": "다큐멘터리",
    "censorship": "검열",
    "freedom": "자유",
    "liberty": "자유",
    "democracy": "민주주의",
    "autocracy": "독재",
    "totalitarian": "전체주의적인",
    "authoritarian": "권위주의적인",
    "sovereignty": "주권",
    "jurisdiction": "관할권",
    "legislation": "입법",
    "regulation": "규제",
    "constitution": "헌법",
    "amendment": "수정안",
    "ratification": "비준",
    "referendum": "국민투표",
    "plebiscite": "국민투표",
    "electoral": "선거의",
    "parliamentary": "의회의",
    "congressional": "의회의",
    "geopolitical": "지정학적인",
    "diplomatic": "외교적인",
    "bilateral": "양자간의",
    "multilateral": "다자간의",
    "macroeconomic": "거시경제적인",
    "microeconomic": "미시경제적인",
    "fiscal": "재정의",
    "monetary": "통화의",
    "inflation": "인플레이션",
    "deflation": "디플레이션",
    "recession": "경기침체",
    "depression": "불황",
    "prosperity": "번영",
    "austerity": "긴축",
    "stimulus": "경기부양",
    "subsidy": "보조금",
    "catastrophe": "재앙",
    "calamity": "재난",
    "disaster": "재해",
    "tragedy": "비극",
    "epidemic": "유행병",
    "pandemic": "팬데믹",
    "endemic": "풍토병의",
    "humanitarian": "인도주의적인",
    "philanthropic": "자선적인",
    "altruistic": "이타적인",
    "benevolent": "선량한",
    "charitable": "자선의",
    "advocacy": "옹호"
}

def get_korean_meaning(word):
    """단어의 한국어 뜻을 반환"""
    return KOREAN_MEANINGS.get(word, word)

def update_json_files():
    """모든 영어 JSON 파일의 meaning_ko 필드를 한국어로 교체"""
    base_path = Path(__file__).parent.parent / "assets" / "data"
    
    # 영어 파일들만 처리
    english_files = [
        "EN_기초다지기_일상회화.json",
        "EN_기초다지기_비즈니스.json", 
        "EN_기초다지기_여행.json",
        "EN_기초다지기_뉴스-시사.json",
        "EN_표현력확장_일상회화.json",
        "EN_표현력확장_비즈니스.json",
        "EN_표현력확장_여행.json", 
        "EN_표현력확장_뉴스-시사.json",
        "EN_원어민수준_일상회화.json",
        "EN_원어민수준_비즈니스.json",
        "EN_원어민수준_여행.json",
        "EN_원어민수준_뉴스-시사.json"
    ]
    
    print("모든 영어 JSON 파일의 meaning_ko 필드를 한국어로 교체하는 중...")
    
    for filename in english_files:
        filepath = base_path / filename
        
        if not filepath.exists():
            print(f"⚠️  파일을 찾을 수 없습니다: {filename}")
            continue
            
        try:
            # JSON 파일 읽기
            with open(filepath, 'r', encoding='utf-8') as f:
                data = json.load(f)
            
            # 각 단어의 meaning_ko 필드 교체
            updated_count = 0
            for item in data:
                if isinstance(item, dict) and 'word' in item and 'meaning_ko' in item:
                    word = item['word']
                    old_meaning = item['meaning_ko']
                    
                    # 영어로 되어있는 경우에만 교체
                    if old_meaning == word or old_meaning.isascii():
                        new_meaning = get_korean_meaning(word)
                        item['meaning_ko'] = new_meaning
                        updated_count += 1
            
            # 파일 저장
            with open(filepath, 'w', encoding='utf-8') as f:
                json.dump(data, f, ensure_ascii=False, indent=2)
            
            print(f"✅ {filename} 업데이트 완료 ({updated_count}개 한국어 뜻 교체)")
            
        except Exception as e:
            print(f"❌ {filename} 처리 중 오류: {e}")
    
    print("\n모든 영어 파일의 meaning_ko 필드 교체 완료! 🎉")

if __name__ == "__main__":
    update_json_files()
