#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
모든 영어 JSON 파일의 예문을 자연스럽게 개선하는 스크립트
"""

import json
import os
from pathlib import Path

# 예문 데이터베이스 - 단어별로 적절한 예문 정의
EXAMPLE_DATABASE = {
    # 기초다지기 일상회화
    "hello": "Hello, how are you today?",
    "yes": "Yes, I would like some coffee.",
    "no": "No, thank you. I'm not hungry.",
    "thank": "Thank you for your help.",
    "please": "Please pass me the salt.",
    "sorry": "Sorry, I'm late for the meeting.",
    "welcome": "Welcome to our home!",
    "bye": "Bye! See you tomorrow.",
    "good": "This is a good book to read.",
    "bad": "The weather is bad today.",
    "help": "Can you help me with this problem?",
    "talk": "Let's talk about your plans.",
    "speak": "I speak English fluently.",
    "listen": "Please listen to the teacher.",
    "ask": "May I ask you a question?",
    "answer": "Can you answer this question?",
    "tell": "Tell me about your vacation.",
    "say": "What did you say?",
    "name": "What's your name?",
    "meet": "Nice to meet you!",
    "friend": "My best friend lives in Seoul.",
    "family": "I love spending time with my family.",
    "happy": "I am happy to see you again.",
    "sad": "She felt sad when her pet died.",
    "like": "I like pizza for dinner.",
    "want": "I want to learn English.",
    "need": "I need some help.",
    "have": "I have a meeting at 3 PM.",
    "get": "I get up early every day.",
    "give": "Please give me the book.",
    "know": "I know the answer.",
    "think": "I think it's a good idea.",
    "feel": "I feel tired today.",
    "see": "I can see the mountains.",
    "hear": "I hear music playing.",
    "come": "Please come to my party.",
    "go": "Let's go to the park.",
    "eat": "I eat breakfast at 7 AM.",
    "drink": "I drink coffee every morning.",
    "sleep": "I sleep eight hours every night.",
    "morning": "Good morning! How are you?",
    "afternoon": "I have a meeting this afternoon.",
    "evening": "Let's go for a walk this evening.",
    "night": "Good night! Sleep well.",
    "today": "What are you doing today?",
    "tomorrow": "I will see you tomorrow.",
    "yesterday": "I went shopping yesterday.",
    "time": "What time is it?",
    "day": "Have a great day!",
    "week": "I work five days a week.",
    
    # 기초다지기 비즈니스
    "work": "I have a lot of work to do today.",
    "job": "My job is to help customers.",
    "office": "Our office is on the 5th floor.",
    "company": "I work for a technology company.",
    "boss": "My boss is very understanding.",
    "manager": "The manager will review your report.",
    "worker": "Every worker needs a break.",
    "team": "Our team works well together.",
    "meeting": "We have a meeting at 3 PM.",
    "email": "Please send me an email with the details.",
    "call": "I will call you later.",
    "phone": "My phone is ringing.",
    "computer": "I use my computer for work.",
    "paper": "Please sign this paper.",
    "pen": "Can I borrow your pen?",
    "desk": "My desk is very organized.",
    "chair": "This chair is comfortable.",
    "file": "I saved the file on my computer.",
    "document": "Please read this document.",
    "report": "The report shows good results.",
    "money": "I need to save more money.",
    "pay": "I pay my bills every month.",
    "salary": "My salary increased this year.",
    "price": "The price is too high.",
    "sell": "We sell quality products.",
    "buy": "I want to buy a new car.",
    "customer": "The customer is always right.",
    "client": "Our client is very satisfied.",
    "service": "We provide excellent service.",
    "product": "This product is very popular.",
    "schedule": "What's your schedule for today?",
    "early": "I wake up early every day.",
    "late": "I'm sorry I'm late.",
    "busy": "I'm very busy this week.",
    "free": "Are you free this weekend?",
    "start": "Let's start the meeting.",
    "finish": "I will finish this project today.",
    "break": "Let's take a break.",
    "lunch": "I eat lunch at noon.",
    "month": "This month is very busy.",
    "year": "This year has been great.",
    "plan": "What's your plan for tomorrow?",
    "goal": "My goal is to learn English.",
    "problem": "We need to solve this problem.",
    "solution": "I found a good solution.",
    
    # 기초다지기 여행
    "trip": "I'm planning a trip to Japan.",
    "travel": "I love to travel around the world.",
    "visit": "I want to visit Paris next year.",
    "arrive": "We will arrive at 3 PM.",
    "leave": "I must leave early tomorrow.",
    "stay": "We will stay for three days.",
    "hotel": "The hotel is near the airport.",
    "room": "Our room has a beautiful view.",
    "airport": "The airport is very busy today.",
    "plane": "The plane leaves at 2 PM.",
    "train": "I take the train to work.",
    "bus": "The bus is coming soon.",
    "taxi": "I need to call a taxi.",
    "car": "I drive my car to work.",
    "ticket": "I bought a ticket for the concert.",
    "passport": "Don't forget your passport.",
    "bag": "I packed my bag for the trip.",
    "luggage": "Where is the luggage claim?",
    "map": "I need a map to find the way.",
    "guide": "The guide showed us the city.",
    "tour": "We took a tour of the museum.",
    "photo": "I took many photos on vacation.",
    "camera": "My camera takes great pictures.",
    "beach": "The beach is beautiful today.",
    "mountain": "I love hiking in the mountains.",
    "city": "This city is very big.",
    "country": "I want to visit many countries.",
    "place": "This is a beautiful place.",
    "food": "The food here is delicious.",
    "restaurant": "Let's go to a restaurant.",
    "shop": "I like to shop for clothes.",
    "buy": "I want to buy souvenirs.",
    "money": "I need to exchange money.",
    "price": "What's the price of this?",
    "cheap": "This hotel is very cheap.",
    "expensive": "This restaurant is too expensive.",
    "book": "I need to book a hotel.",
    "reserve": "I want to reserve a table.",
    "check": "Please check the time.",
    "in": "Come in, please.",
    "out": "Let's go out for dinner.",
    "lost": "I'm lost. Can you help me?",
    "find": "I can't find my keys.",
    "where": "Where is the bathroom?",
    "when": "When does the train leave?",
    "how": "How do I get to the station?",
    "far": "How far is the hotel?",
    
    # 기초다지기 뉴스-시사
    "news": "I watch the news every evening.",
    "report": "The weather report says it will rain.",
    "story": "This is an interesting story.",
    "read": "I read the newspaper every morning.",
    "watch": "I watch TV news at 6 PM.",
    "listen": "I listen to the radio in the car.",
    "tell": "Tell me what happened.",
    "know": "I know the latest news.",
    "hear": "I heard about the accident.",
    "see": "I saw it on television.",
    "today": "What happened today?",
    "now": "What's happening now?",
    "new": "This is a new development.",
    "old": "That's old news.",
    "big": "This is a big story.",
    "small": "It's a small problem.",
    "important": "This is very important news.",
    "happen": "What happened yesterday?",
    "event": "This is a major event.",
    "thing": "This is a serious thing.",
    "people": "Many people are talking about this.",
    "person": "This person is famous.",
    "man": "The man is a politician.",
    "woman": "The woman is a journalist.",
    "child": "The child is safe now.",
    "place": "This place is in the news.",
    "city": "The city is in trouble.",
    "country": "The country is at war.",
    "world": "This affects the whole world.",
    "home": "I'm going home now.",
    "good": "This is good news.",
    "bad": "This is bad news.",
    "right": "This is the right thing to do.",
    "wrong": "This is wrong.",
    "true": "Is this true?",
    "false": "This is false information.",
    "say": "What did they say?",
    "talk": "Let's talk about the news.",
    "speak": "The president will speak today.",
    "ask": "I want to ask a question.",
    "answer": "Can you answer this?",
    "think": "What do you think?",
    "believe": "I believe this is true.",
    "feel": "How do you feel about this?",
    "like": "I like this news.",
    "want": "I want to know more.",
    "need": "We need more information.",
    "help": "Can you help me understand?",
    "problem": "This is a serious problem.",
    "change": "Things need to change.",
    
    # 표현력확장 레벨
    "conversation": "We had a long conversation about politics.",
    "discuss": "Let's discuss the project details tomorrow.",
    "explain": "Can you explain how this works?",
    "describe": "Please describe what you saw yesterday.",
    "opinion": "What is your opinion on this matter?",
    "agree": "I agree with your point.",
    "disagree": "I disagree with that statement.",
    "suggest": "I suggest we meet tomorrow.",
    "recommend": "I recommend this restaurant.",
    "advice": "Can you give me some advice?",
    "apologize": "I apologize for the mistake.",
    "compliment": "That's a nice compliment.",
    "introduce": "Let me introduce myself.",
    "interrupt": "Sorry to interrupt you.",
    "mention": "Did you mention the meeting?",
    "express": "I want to express my gratitude.",
    "communicate": "We need to communicate better.",
    "understand": "I understand your concern.",
    "misunderstand": "I think you misunderstood me.",
    "clarify": "Can you clarify that point?",
    "confirm": "Please confirm your attendance.",
    "remind": "Let me remind you about the meeting.",
    "promise": "I promise to be on time.",
    "refuse": "I refuse to accept this.",
    "accept": "I accept your offer.",
    "reject": "I reject this proposal.",
    "persuade": "I will try to persuade them.",
    "argue": "Let's not argue about this.",
    "debate": "We had a heated debate.",
    "negotiate": "We need to negotiate the terms.",
    "gossip": "Don't spread gossip.",
    "rumor": "That's just a rumor.",
    "whisper": "She whispered in my ear.",
    "shout": "Don't shout at me.",
    "mumble": "He mumbled his response.",
    "stutter": "He stuttered when nervous.",
    "emphasize": "I want to emphasize this point.",
    "imply": "What are you implying?",
    "comment": "That's an interesting comment.",
    "remark": "That's a clever remark.",
    "statement": "This is an official statement.",
    "question": "I have a question for you.",
    "response": "Thank you for your response.",
    "feedback": "I appreciate your feedback.",
    "criticism": "I accept constructive criticism.",
    "praise": "I deserve this praise.",
    "gesture": "That was a kind gesture.",
    "expression": "Your expression shows concern.",
    "tone": "Your tone is too harsh.",
    "attitude": "I like your positive attitude.",
    
    # 비즈니스 원어민수준 용어
    "corporation": "The corporation announced record profits this quarter.",
    "enterprise": "This is a successful enterprise with global reach.",
    "organization": "Our organization focuses on sustainable development.",
    "department": "The marketing department is launching a new campaign.",
    "employee": "Every employee receives comprehensive health benefits.",
    "colleague": "My colleague is very helpful.",
    "supervisor": "My supervisor approved the project.",
    "executive": "The executive team met yesterday.",
    "director": "The director made an important decision.",
    "administrator": "The administrator handles the system.",
    "position": "I applied for a new position.",
    "responsibility": "This is my responsibility.",
    "assignment": "I have a new assignment.",
    "project": "This project is very important.",
    "deadline": "The deadline is next Friday.",
    "presentation": "I have a presentation tomorrow.",
    "proposal": "I submitted my proposal yesterday.",
    "contract": "Please sign the contract.",
    "agreement": "We reached an agreement.",
    "negotiation": "The negotiation was successful.",
    "transaction": "This is a large transaction.",
    "investment": "This is a good investment.",
    "profit": "The company made a profit.",
    "loss": "We suffered a loss this quarter.",
    "revenue": "Our revenue increased this year.",
    "expense": "We need to reduce expenses.",
    "budget": "The budget was approved.",
    "finance": "I work in finance.",
    "accounting": "The accounting department is busy.",
    "marketing": "Marketing is essential for success.",
    "advertising": "The advertising campaign was successful.",
    "sales": "Sales increased this month.",
    "distribution": "Distribution is handled by our partner.",
    "supply": "We have a good supply of materials.",
    "demand": "Demand for our product is high.",
    "inventory": "We need to check our inventory.",
    "stock": "Our stock price is rising.",
    "quality": "Quality is our top priority.",
    "efficiency": "We improved our efficiency.",
    "productivity": "Productivity increased this year.",
    "performance": "Your performance is excellent.",
    "evaluation": "The evaluation was positive.",
    "feedback": "I appreciate your feedback.",
    "promotion": "I got a promotion last month.",
    "recruitment": "Recruitment is ongoing.",
    "training": "Training is provided for all employees.",
    "competition": "Competition is fierce in this market.",
    "strategy": "Our strategy is working well.",
    "analysis": "The analysis shows positive results.",
    "research": "Research is important for innovation.",
    
    # 여행 원어민수준 용어
    "destination": "Paris is my favorite travel destination.",
    "itinerary": "Please send me the detailed itinerary for our trip.",
    "reservation": "I need to confirm my hotel reservation.",
    "accommodation": "The accommodation includes breakfast and WiFi.",
    "departure": "Our departure time is 8:30 AM tomorrow.",
    "arrival": "Our arrival is scheduled for 3 PM.",
    "boarding": "Boarding begins in 30 minutes.",
    "customs": "We need to go through customs.",
    "immigration": "Immigration took an hour.",
    "security": "Security is very strict here.",
    "baggage": "Where is the baggage claim?",
    "suitcase": "My suitcase is heavy.",
    "backpack": "I travel with a backpack.",
    "traveler": "I'm an experienced traveler.",
    "tourist": "Many tourists visit this place.",
    "vacation": "I'm on vacation this week.",
    "holiday": "I'm taking a holiday next month.",
    "adventure": "This is a great adventure.",
    "excursion": "We planned a day excursion to the nearby islands.",
    "sightseeing": "We did a lot of sightseeing.",
    "landmark": "This is a famous landmark.",
    "monument": "The monument is very old.",
    "museum": "The museum is free on Sundays.",
    "gallery": "The art gallery is beautiful.",
    "attraction": "This is a popular tourist attraction.",
    "scenic": "The scenic route is beautiful.",
    "hospitality": "The hospitality here is excellent.",
    "reception": "The hotel reception is helpful.",
    "concierge": "The concierge can help you.",
    "amenities": "The hotel has great amenities.",
    "facilities": "The facilities are modern.",
    "transportation": "Public transportation is convenient.",
    "schedule": "What's the schedule for today?",
    "delay": "There's a delay due to weather.",
    "cancellation": "The cancellation policy is strict.",
    "refund": "I want a refund for my ticket.",
    "exchange": "I need to exchange currency.",
    "currency": "What's the local currency?",
    "souvenir": "I bought many souvenirs.",
    "local": "Ask the local people for advice.",
    "native": "The native language is Spanish.",
    "foreign": "I'm a foreign visitor.",
    "international": "This is an international flight.",
    "domestic": "This is a domestic flight.",
    "culture": "I love learning about different cultures.",
    "tradition": "This is an old tradition.",
    "explore": "Let's explore the city.",
    "discover": "I want to discover new places.",
    "wander": "I like to wander around.",
    "navigate": "I need to navigate carefully.",
    
    # 뉴스-시사 원어민수준 용어
    "journalism": "Investigative journalism plays a crucial role in democracy.",
    "reporter": "The reporter covered the breaking news story.",
    "correspondent": "Our foreign correspondent reported from the scene.",
    "editor": "The editor reviewed the article before publication.",
    "publisher": "The publisher decided to release the book next month.",
    "broadcast": "The broadcast was interrupted by breaking news.",
    "media": "The media is covering this story extensively.",
    "press": "The press conference is at 2 PM.",
    "newspaper": "I read the newspaper every morning.",
    "magazine": "This magazine has great articles.",
    "article": "This article is very informative.",
    "headline": "The headline caught my attention.",
    "coverage": "The coverage was comprehensive.",
    "investigation": "The investigation is ongoing.",
    "interview": "The interview was very interesting.",
    "statement": "The official statement was released.",
    "announcement": "The announcement surprised everyone.",
    "declaration": "The declaration was made public.",
    "disclosure": "The disclosure revealed important information.",
    "revelation": "This revelation shocked everyone.",
    "incident": "The incident occurred yesterday.",
    "occurrence": "This occurrence is unusual.",
    "development": "This is a significant development.",
    "situation": "The situation is under control.",
    "circumstance": "Under these circumstances, we must act.",
    "condition": "The condition is stable.",
    "politics": "Politics is a complex subject.",
    "government": "The government announced new policies.",
    "election": "The election is next month.",
    "policy": "This policy affects everyone.",
    "economy": "The economy is improving.",
    "market": "The market is volatile.",
    "crisis": "We're facing a crisis.",
    "conflict": "The conflict continues.",
    "dispute": "The dispute was resolved.",
    "controversy": "This controversy is ongoing.",
    "debate": "The debate was heated.",
    "discussion": "The discussion was productive.",
    "opinion": "Everyone has a different opinion.",
    "perspective": "From my perspective, this is wrong.",
    "analysis": "The analysis is thorough.",
    "commentary": "The political commentary provided insightful analysis.",
    "criticism": "The criticism was harsh.",
    "review": "The review was positive.",
    "evaluation": "The evaluation was fair.",
    "assessment": "The assessment is complete.",
    "survey": "The survey shows interesting results.",
    "statistics": "The statistics are alarming.",
    "data": "The data supports our theory.",
    "evidence": "The evidence is compelling.",
    "proof": "We need more proof.",
    
    # 원어민수준 원어민수준 용어
    "articulate": "She is very articulate when discussing complex topics.",
    "eloquent": "His eloquent speech moved the entire audience.",
    "rhetoric": "Political rhetoric often obscures the real issues.",
    "diplomatic": "She handled the situation in a diplomatic manner.",
    "tactful": "He was tactful in declining the invitation.",
    "assertive": "You need to be more assertive.",
    "confrontation": "We want to avoid confrontation.",
    "mediation": "Mediation helped resolve the dispute.",
    "reconciliation": "Reconciliation is possible.",
    "discourse": "The discourse was academic.",
    "dialogue": "The dialogue was constructive.",
    "monologue": "His monologue was too long.",
    "soliloquy": "The soliloquy was dramatic.",
    "vernacular": "The vernacular is different here.",
    "colloquial": "This is colloquial language.",
    "jargon": "Avoid using too much jargon.",
    "euphemism": "This is a euphemism for death.",
    "metaphor": "The metaphor was beautiful.",
    "analogy": "The analogy was helpful.",
    "inference": "The inference was logical.",
    "connotation": "The connotation is negative.",
    "denotation": "The denotation is clear.",
    "ambiguity": "There's ambiguity in this statement.",
    "nuance": "The nuance is subtle.",
    "subtlety": "The subtlety was lost on them.",
    "implication": "The implication is serious.",
    "persuasion": "Persuasion is an art.",
    "manipulation": "This is manipulation.",
    "propaganda": "The regime used propaganda to control public opinion.",
    "eloquence": "His eloquence was impressive.",
    "articulation": "The articulation was clear.",
    "deliberation": "The deliberation took hours.",
    "contemplation": "Contemplation is necessary.",
    "rumination": "His rumination was deep.",
    "introspection": "Introspection is valuable.",
    "retrospection": "Retrospection brings wisdom.",
    "philosophical": "This is a philosophical question.",
    "theoretical": "The theoretical framework is sound.",
    "abstract": "This concept is too abstract.",
    "conceptual": "The conceptual design is good.",
    "hypothetical": "This is a hypothetical situation.",
    "speculative": "The speculation was unfounded.",
    "intellectual": "This is an intellectual discussion.",
    "cognitive": "Cognitive abilities vary.",
    "analytical": "She has analytical skills.",
    "critical": "Critical thinking is important.",
    "rational": "Be rational about this.",
    "logical": "The logical conclusion is clear.",
    
    # 원어민수준 비즈니스 용어
    "conglomerate": "The multinational conglomerate operates in 50 countries.",
    "subsidiary": "The company established a subsidiary in Asia.",
    "affiliate": "Our affiliate program generates significant revenue.",
    "merger": "The merger created the largest tech company in the industry.",
    "acquisition": "The acquisition strategy expanded our market share.",
    "consolidation": "The consolidation reduced costs.",
    "restructuring": "The restructuring was necessary.",
    "diversification": "Diversification reduces risk.",
    "specialization": "Specialization improves efficiency.",
    "monopoly": "The monopoly was broken up.",
    "oligopoly": "The oligopoly controls prices.",
    "entrepreneurship": "Entrepreneurship drives innovation.",
    "venture": "This is a risky venture.",
    "startup": "The startup is growing fast.",
    "innovation": "Innovation is key to success.",
    "disruption": "This technology causes disruption.",
    "transformation": "Digital transformation is essential.",
    "sustainability": "Sustainability is our priority.",
    "scalability": "Scalability is important for growth.",
    "optimization": "Optimization improves performance.",
    "automation": "Automation reduces costs.",
    "digitalization": "Digitalization is inevitable.",
    "stakeholder": "All stakeholders were consulted.",
    "shareholder": "Shareholders expect returns.",
    "dividend": "The dividend was increased.",
    "equity": "Equity financing was chosen.",
    "liability": "The liability is limited.",
    "asset": "This is a valuable asset.",
    "depreciation": "Depreciation affects profits.",
    "amortization": "Amortization spreads costs.",
    "valuation": "The valuation was high.",
    "liquidation": "Liquidation was necessary.",
    "bankruptcy": "Bankruptcy was declared.",
    "insolvency": "Insolvency was avoided.",
    "foreclosure": "Foreclosure was prevented.",
    "compliance": "Compliance is mandatory.",
    "regulation": "Regulation is increasing.",
    "legislation": "New legislation was passed.",
    "litigation": "Litigation is expensive.",
    "arbitration": "Arbitration was chosen.",
    "mediation": "Mediation resolved the dispute.",
    "intellectual": "Intellectual property is valuable.",
    "proprietary": "This is proprietary information.",
    "patent": "The patent was granted.",
    "trademark": "The trademark was registered.",
    "copyright": "Copyright protection is important.",
    "franchise": "The franchise is successful.",
    "syndicate": "The syndicate was formed.",
    "consortium": "The consortium was established.",
    "collaboration": "Collaboration is essential.",
    "partnership": "The partnership is strong.",
    "alliance": "The alliance was formed.",
    "cooperation": "Cooperation is necessary.",
    
    # 원어민수준 여행 용어
    "expedition": "The mountain expedition required extensive preparation.",
    "pilgrimage": "Many people make a pilgrimage to Mecca annually.",
    "odyssey": "Their journey became an unforgettable odyssey.",
    "sojourn": "His sojourn in Paris lasted three months.",
    "itinerant": "He leads an itinerant lifestyle.",
    "nomadic": "The nomadic tribes move seasonally.",
    "cosmopolitan": "This is a cosmopolitan city.",
    "expatriate": "The expatriate community is large.",
    "diaspora": "The diaspora maintains cultural ties.",
    "displacement": "Displacement caused hardship.",
    "migration": "Migration patterns are changing.",
    "emigration": "Emigration increased this year.",
    "colonization": "Colonization had lasting effects.",
    "exploration": "Exploration opened new frontiers.",
    "pioneering": "Pioneering work was done here.",
    "traversal": "The traversal was difficult.",
    "circumnavigation": "Circumnavigation was achieved.",
    "embarkation": "Embarkation begins at 2 PM.",
    "disembarkation": "Disembarkation is at 4 PM.",
    "layover": "The layover is three hours.",
    "stopover": "We have a stopover in Dubai.",
    "transit": "Transit passengers go to gate 12.",
    "consulate": "The consulate is downtown.",
    "embassy": "The embassy is closed today.",
    "jurisdiction": "This is outside our jurisdiction.",
    "sovereignty": "Sovereignty is respected.",
    "territory": "This territory is disputed.",
    "frontier": "The frontier is dangerous.",
    "boundary": "The boundary is clearly marked.",
    "demarcation": "Demarcation was completed.",
    "infrastructure": "Infrastructure needs improvement.",
    "logistics": "Logistics are complex.",
    "provisions": "Provisions are adequate.",
    "sustenance": "Sustenance is provided.",
    "subsistence": "Subsistence farming is common.",
    "indigenous": "Indigenous people were consulted.",
    "aboriginal": "Aboriginal rights are protected.",
    "ethnic": "Ethnic diversity is celebrated.",
    "multicultural": "This is a multicultural society.",
    "intercultural": "Intercultural dialogue is important.",
    "transnational": "Transnational cooperation is needed.",
    "globalization": "Globalization has benefits and costs.",
    "acculturation": "Acculturation takes time.",
    "assimilation": "Assimilation is gradual.",
    "adaptation": "Adaptation is necessary.",
    "orientation": "Orientation is provided.",
    "disorientation": "Disorientation is common.",
    "alienation": "Alienation can be prevented.",
    
    # 원어민수준 뉴스-시사 용어
    "investigative": "Investigative journalism uncovered the corruption scandal.",
    "editorial": "The newspaper's editorial criticized the government policy.",
    "documentary": "The documentary exposed environmental violations.",
    "censorship": "Media censorship restricts freedom of expression.",
    "freedom": "Freedom of speech is fundamental.",
    "liberty": "Liberty must be protected.",
    "democracy": "Democracy requires participation.",
    "autocracy": "Autocracy suppresses dissent.",
    "totalitarian": "Totalitarian regimes are oppressive.",
    "authoritarian": "Authoritarian rule is dangerous.",
    "sovereignty": "National sovereignty is important.",
    "jurisdiction": "Jurisdiction is clearly defined.",
    "legislation": "New legislation was proposed.",
    "regulation": "Regulation is necessary.",
    "constitution": "The constitution guarantees rights.",
    "amendment": "The amendment was ratified.",
    "ratification": "Ratification requires approval.",
    "referendum": "The referendum was held.",
    "plebiscite": "The plebiscite was successful.",
    "electoral": "Electoral reform is needed.",
    "parliamentary": "Parliamentary democracy works.",
    "congressional": "Congressional hearings were held.",
    "geopolitical": "Geopolitical tensions are rising.",
    "diplomatic": "Diplomatic relations improved.",
    "bilateral": "Bilateral agreements were signed.",
    "multilateral": "Multilateral cooperation is essential.",
    "macroeconomic": "Macroeconomic policies matter.",
    "microeconomic": "Microeconomic factors influence decisions.",
    "fiscal": "Fiscal responsibility is important.",
    "monetary": "Monetary policy affects inflation.",
    "inflation": "Inflation is rising.",
    "deflation": "Deflation is dangerous.",
    "recession": "Recession is likely.",
    "depression": "Depression was avoided.",
    "prosperity": "Prosperity is shared.",
    "austerity": "Austerity measures were implemented.",
    "stimulus": "Stimulus packages were approved.",
    "subsidy": "Subsidies support agriculture.",
    "catastrophe": "The catastrophe was devastating.",
    "calamity": "The calamity affected millions.",
    "disaster": "The disaster was natural.",
    "tragedy": "The tragedy was preventable.",
    "epidemic": "The epidemic spread quickly.",
    "pandemic": "The pandemic changed everything.",
    "endemic": "The disease is endemic.",
    "humanitarian": "Humanitarian aid was provided.",
    "philanthropic": "Philanthropic efforts increased.",
    "altruistic": "Altruistic behavior is admirable.",
    "benevolent": "Benevolent organizations help.",
    "charitable": "Charitable giving increased.",
    "advocacy": "Advocacy groups are active."
}

def get_example_sentence(word):
    """단어에 대한 적절한 예문을 반환"""
    return EXAMPLE_DATABASE.get(word, f"I use {word} in my daily life.")

def update_json_files():
    """모든 영어 JSON 파일의 예문을 개선"""
    base_path = Path(__file__).parent.parent / "assets" / "data"
    
    # 영어 파일들만 처리
    english_files = [
        "EN_기초다지기_일상회화.json",
        "EN_기초다지기_비즈니스.json", 
        "EN_기초다지기_여행.json",
        "EN_기초다지기_뉴스-시사.json",
        "EN_표현력확장_일상회화.json",
        "EN_표현력확장_비즈니스.json",
        "EN_표현력확장_여행.json", 
        "EN_표현력확장_뉴스-시사.json",
        "EN_원어민수준_일상회화.json",
        "EN_원어민수준_비즈니스.json",
        "EN_원어민수준_여행.json",
        "EN_원어민수준_뉴스-시사.json"
    ]
    
    print("모든 영어 JSON 파일의 예문을 개선하는 중...")
    
    for filename in english_files:
        filepath = base_path / filename
        
        if not filepath.exists():
            print(f"⚠️  파일을 찾을 수 없습니다: {filename}")
            continue
            
        try:
            # JSON 파일 읽기
            with open(filepath, 'r', encoding='utf-8') as f:
                data = json.load(f)
            
            # 각 단어의 예문 개선
            updated_count = 0
            for item in data:
                if isinstance(item, dict) and 'word' in item and 'example' in item:
                    word = item['word']
                    old_example = item['example']
                    
                    # 템플릿 예문인 경우에만 교체
                    if old_example == f"This is an example with {word}.":
                        new_example = get_example_sentence(word)
                        item['example'] = new_example
                        updated_count += 1
            
            # 파일 저장
            with open(filepath, 'w', encoding='utf-8') as f:
                json.dump(data, f, ensure_ascii=False, indent=2)
            
            print(f"✅ {filename} 업데이트 완료 ({updated_count}개 예문 개선)")
            
        except Exception as e:
            print(f"❌ {filename} 처리 중 오류: {e}")
    
    print("\n모든 영어 파일의 예문 개선 완료! 🎉")

if __name__ == "__main__":
    update_json_files()
